<div class="row">
    <div class="col-md-9">
        <div class="btn-group">
            <button ng-click="increaseZoom();">Increase Zoom</button>
            <button ng-click="decreaseZoom();">Descrease Zoom</button>
            <span>Current Zoom: {{zoom}}</span>
        </div>
        <google-map
            center="center"
            draggable="true"
            zoom="zoom"
            markers="markers"
            mark-click="true"
            style="height: 400px; display: block;"
            >
        </google-map>
    </div>
    <div class="col-md-3">
        <div class="btn-group">
            <button ng-click="getMarkers();">Get Markers</button>
        </div>
        <div ng-repeat="marker in markers">
            <div class="item">
                <p>Latitude: {{marker.latitude}}</p>
                <p>Longitude: {{marker.longitude}}</p>
            </div>
        </div>
    </div>
</div>


<style type="text/css">
    p{
        margin: 0px;
    }
    .angular-google-map,
    .angular-google-map-container,
    .gm-style
    {
        height: 400px;
    }

    .btn-group{
        margin-bottom: 10px;
    }

    .item {
        margin-bottom: 10px;
    }
</style>